version: '3'
services:
  graph-node:
    image: 'graphprotocol/graph-node:v0.18.0'
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
    links:
      - ipfs
      - postgres
    environment:
      postgres_host: 'postgres:5432'
      postgres_user: postgres
      postgres_pass: letmein
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      ethereum: 'goerli:https://goerli.infura.io/v3/6141be73a15d47748af0dc14f53d57d7'
      GRAPH_IPFS_TIMEOUT: '2'
      GRAPH_MAX_IPFS_FILE_BYTES: '800000'
      GRAPH_GRAPHQL_MAX_FIRST: '1000'
  ipfs:
    image: 'ipfs/go-ipfs:v0.4.23'
    ports:
      - '5001:5001'
  postgres:
    build: docker/postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: letmein
